site_name: rts
site_description: rts retas package documentation
site_author: Irfannur Diah
site_url: https://retas.readthedocs.io

repo_url: https://github.com/irfnrdh/rts/
edit_uri: tree/master/docs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
      - Basic: usage/basic.md
  - Tests: tests.md
  - API: api.md
  - Changelog: changelog.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      css_class: highlight